FROM ubuntu:18.04

MAINTAINER EB2-2027

RUN apt-get update
RUN apt-get -y install iproute2
RUN apt-get -y install telnet
RUN apt-get -y install openssh-server
RUN apt-get -y install iptables
RUN apt-get -y install iputils-ping
RUN apt-get -y install traceroute
RUN apt-get -y install tcpdump
RUN apt-get -y install iperf
RUN apt-get -y install vim
RUN apt-get -y install python
RUN apt-get -y install python-pip
RUN apt-get -y install curl
RUN apt-get -y install lsb-release
RUN pip install --upgrade pip
RUN apt-get -y  install python-pexpect
RUN pip install paramiko
RUN apt-get -y  install nano
RUN apt-get -y  install bridge-utils
RUN apt-get -y  install apt-transport-https
RUN apt-get -y install nmap
#RUN apt-get -y quagga 

RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump
RUN ln -s /usr/bin/tcpdump /usr/sbin/tcpdump
#RUN cp /usr/share/doc/quagga/examples/zebra.conf.sample /etc/quagga/zebra.conf
#RUN cp /usr/share/doc/quagga/examples/bgpd.conf.sample /etc/quagga/bgpd.conf
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

#RUN chown quagga:quagga /etc/quagga/*.conf
#RUN chown quagga:quaggavty /etc/quagga/*.conf
#RUN chmod 640 /etc/quagga/*.conf

RUN apt-get -y install nginx
RUN apt-get -y install bind9
RUN apt-get -y install gcc g++ wget git unzip keepalived
#RUN apt-get install firewalld

EXPOSE 22
EXPOSE 53
EXPOSE 80
EXPOSE 443
CMD ["tail","-f","/dev/null"]
